### ISSUE TITLE
[Request for info] How to use values? 

### ISSUE THREAD

**Issue by woody4165** [vukmirovic98/node-red-contrib-covid19#1]
Hi 

Thanks for this node, first of all.

When I try to use an attribute of a country, the path proposed is

msg.["covid-19"].IT.cases

but if I try to copy in msg.it_casi I get this error 

![Schermata 2020-03-27 alle 20 45 10](https://user-images.githubusercontent.com/6501444/77794286-e55b5100-706b-11ea-991f-bc04f29d470f.png)

i've tried also with msg.covid-19.IT.cases but I get this

![Schermata 2020-03-27 alle 20 46 38](https://user-images.githubusercontent.com/6501444/77794396-19cf0d00-706c-11ea-8525-55a928ca9f52.png)

Do you have any suggestion?

Thanks

**Comment by vukmirovic98** [comment]
I Didn't planned this will be an issue, i am currently working on another
problem in the code, but i will remove the '-19' from the msg. And will
update the version in 24-48h.
Thank you sir for reporting. If you actually need to use the node while i
am working.I think you could use a change node to change covid-19 to covid.
You could try to do that and please tell me if that worked for you.
Have a nice day and stay safe...

пет, 27. мар 2020. 20:47 woody4165 <notifications@github.com> је написао/ла:

**Comment by woody4165** [comment]
Thanks @vukmirovic98 
Take your time!

I've tried also the change node, but it doesn't work (see the red around the to field).

![Schermata 2020-03-27 alle 21 03 00](https://user-images.githubusercontent.com/6501444/77795783-6b789700-706e-11ea-99e7-6bac775dd0aa.png)

**Comment by vukmirovic98** [comment]
Version 1.1.0 is available on NPM (will probably need 1-2h to be updated on pallet manager). 
**msg.covid19 is changed to msg.covid**
**Functionality and stability fix**
**Status messages are fixed**
![image](https://user-images.githubusercontent.com/53474043/77803617-d7aec700-707d-11ea-9dc1-3c326a5b4388.png)

Thank you for reporting this issue.
I am going to close this issue now.

**Comment by bonastreyair** [comment]
The real problem was the parsing with a dot before a bracket parsing.

```
msg[“covid-19”]    - good parsing
msg.[“covid-19”]   - bad parsing
```

Check this [stackoverflow](https://stackoverflow.com/questions/10311361/accessing-json-object-keys-having-spaces) information.

**Comment by vukmirovic98** [comment]
Thank you for your help @bonastreyair  I do not have much experience in javascript, so all of the programming I do involves a lot of testing a deploying the custom node to node-red. 
As I mentioned above if you have any further problems please create an issue and I will do my best to fix it as fast as possible.
