### ISSUE TITLE
How to get worldwide cases?

### ISSUE THREAD

**Issue by dddhhhrrr** [vukmirovic98/node-red-contrib-covid19#2]
Hi. Thanks for the node. great work. 

Is there a way to get the worldwide cases other than getting the cases of each country and adding them? I tried a few different ways and couldn't get it to work, and the underlying API does provide a way to do it. Thanks!

**Comment by vukmirovic98** [comment]
Hello, sorry for the late reply, actually there is not a way to get the worldwide case number, I am currently working on another project, and I believe i can add another node to gather the world wide case numbers (something like the current node, just without the countries textbox.

**Comment by vukmirovic98** [comment]
Version 2.0.0 is out, will be in the pallet as soon as the node-red index it.
